// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmaFestHub.Infrastructure.Data;

#nullable disable

namespace UmaFestHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.AwardNomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreditFilmId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FestivalFilmId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("CreditFilmId");

                    b.HasIndex("FestivalFilmId");

                    b.ToTable("AwardNominations");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CartId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("EarlyBirdDaysBeforeStart")
                        .HasColumnType("int");

                    b.Property<decimal?>("EarlyBirdDiscountPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Festivals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d96b6b25-2b87-4e10-8f50-6d194ab49022"),
                            Description = "Join us for a week of independent and international films celebrating diverse storytelling.",
                            EndDateUtc = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsHidden = false,
                            Name = "Uma Spring Fest",
                            StartDateUtc = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.FestivalFilm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsWorldPremier")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProgrammingNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("FestivalId", "FilmId")
                        .IsUnique();

                    b.ToTable("FestivalFilms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d690e52-e89c-4b9d-b994-7f4e67d9e323"),
                            AddedAtUtc = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("d96b6b25-2b87-4e10-8f50-6d194ab49022"),
                            FilmId = new Guid("6e75788b-0a9c-4602-a5de-e53a1f6d3a01"),
                            IsWorldPremier = false,
                            ProgrammingNotes = ""
                        });
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Film", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("TmdbPopularity")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e75788b-0a9c-4602-a5de-e53a1f6d3a01"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seed film for initial local development.",
                            ExternalId = 1001,
                            Name = "Midnight Frames",
                            TmdbPopularity = 0m,
                            Url = "https://example.com/midnight-frames"
                        });
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcknowledgedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetUserRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TemplateJson")
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("TargetUserId", "AcknowledgedUtc");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.PersonalList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId", "Type", "FilmId")
                        .IsUnique();

                    b.ToTable("PersonalLists");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("ProductType").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExternalFilmId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FestivalFilmId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FilmId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("HasBeenReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHiddenByAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FestivalFilmId");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.ReviewReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasBeenReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHiddenByAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewReplies");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FestivalFilmId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FestivalFilmId");

                    b.ToTable("Sessions");

                    b.HasDiscriminator<string>("SessionType").HasValue("Session");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AwardNominationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "AwardNominationId");

                    b.HasIndex("AwardNominationId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("UmaFestHub.Domain.ValueObjects.CreditFilm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("PersonId");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("UmaFestHub.Domain.ValueObjects.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("UmaFestHub.Domain.ValueObjects.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Pass", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Product");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("char(36)");

                    b.HasIndex("FestivalId");

                    b.HasDiscriminator().HasValue("Pass");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Rental", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Product");

                    b.Property<Guid>("FestivalFilmId")
                        .HasColumnType("char(36)");

                    b.HasIndex("FestivalFilmId");

                    b.HasDiscriminator().HasValue("Rental");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Ticket", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Product");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasIndex("SessionId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Ticket");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.AccessWindowSession", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Session");

                    b.HasDiscriminator().HasValue("AccessWindowSession");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.FixedSession", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Session");

                    b.HasDiscriminator().HasValue("FixedSession");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.PremierSession", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Session");

                    b.HasDiscriminator().HasValue("PremierSession");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.CompletePass", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Pass");

                    b.HasDiscriminator().HasValue("CompletePass");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.DailyPass", b =>
                {
                    b.HasBaseType("UmaFestHub.Domain.Entities.Pass");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime(6)");

                    b.HasDiscriminator().HasValue("DailyPass");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Award", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Festival", "Festival")
                        .WithMany("Awards")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.AwardNomination", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Award", "Award")
                        .WithMany("Nominations")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.ValueObjects.CreditFilm", "CreditFilm")
                        .WithMany()
                        .HasForeignKey("CreditFilmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmaFestHub.Domain.Entities.FestivalFilm", "FestivalFilm")
                        .WithMany("AwardNomination")
                        .HasForeignKey("FestivalFilmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Award");

                    b.Navigation("CreditFilm");

                    b.Navigation("FestivalFilm");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Cart", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.FestivalFilm", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Festival", "Festival")
                        .WithMany("FestivalFilms")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.Entities.Film", "Film")
                        .WithMany("FestivalFilms")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Film", b =>
                {
                    b.OwnsOne("UmaFestHub.Domain.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("FilmId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("FilmDurationUnit");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("FilmDurationValue");

                            b1.HasKey("FilmId");

                            b1.ToTable("Films");

                            b1.WithOwner()
                                .HasForeignKey("FilmId");

                            b1.HasData(
                                new
                                {
                                    FilmId = new Guid("6e75788b-0a9c-4602-a5de-e53a1f6d3a01"),
                                    Unit = "Minutes",
                                    Value = 112
                                });
                        });

                    b.Navigation("Duration")
                        .IsRequired();
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Notification", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.PersonalList", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.Entities.User", "User")
                        .WithMany("PersonalLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.PurchaseItem", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Product", "Product")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Review", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.FestivalFilm", "FestivalFilm")
                        .WithMany("Reviews")
                        .HasForeignKey("FestivalFilmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmaFestHub.Domain.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UmaFestHub.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FestivalFilm");

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.ReviewReply", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Review", "Review")
                        .WithMany("Replies")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.Entities.User", "User")
                        .WithMany("ReviewReplies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Session", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.FestivalFilm", "FestivalFilm")
                        .WithMany("Sessions")
                        .HasForeignKey("FestivalFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FestivalFilm");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Vote", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.AwardNomination", "AwardNomination")
                        .WithMany("Votes")
                        .HasForeignKey("AwardNominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardNomination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UmaFestHub.Domain.ValueObjects.CreditFilm", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Film", "Film")
                        .WithMany("Credits")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UmaFestHub.Domain.ValueObjects.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("UmaFestHub.Domain.ValueObjects.Genre", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Film", "Film")
                        .WithMany("Genres")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Pass", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Festival", "Festival")
                        .WithMany("Passes")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Rental", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.FestivalFilm", "FestivalFilm")
                        .WithMany("Rentals")
                        .HasForeignKey("FestivalFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UmaFestHub.Domain.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("RentalId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("DurationUnit");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("DurationValue");

                            b1.HasKey("RentalId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("FestivalFilm");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("UmaFestHub.Domain.Entities.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Award", b =>
                {
                    b.Navigation("Nominations");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.AwardNomination", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Festival", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("FestivalFilms");

                    b.Navigation("Passes");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.FestivalFilm", b =>
                {
                    b.Navigation("AwardNomination");

                    b.Navigation("Rentals");

                    b.Navigation("Reviews");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Film", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("FestivalFilms");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Review", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.Session", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("UmaFestHub.Domain.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("PersonalLists");

                    b.Navigation("Purchases");

                    b.Navigation("ReviewReplies");

                    b.Navigation("Reviews");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
